
apiVersion: v1
kind: Secret
metadata:
  name: clustergroup-name-secret
  namespace: vmware-system-tmc
data:
  groupname: apa-test

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: clustergroup-name-secret
  namespace: vmware-system-tmc
spec:
  toNamespace: '*'

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: clustergroup-name-secret
  namespace: tanzu-continuousdelivery-resources
spec:
  fromNamespace: vmware-system-tmc
  